
 Fri, 30 Oct 2020 21:25:01 GMT

COMMAND LINE:
 /usr/lib/jvm/java-8-graalvm/bin/graalpython fasta.graal-3.graal 2500000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "/home/dundee/work/pybenchmarks/bencher/programs/fasta/fasta.python3-3.python3", line 138, in <module 'fasta.python3-3.python3'>
    main()
  File "/home/dundee/work/pybenchmarks/bencher/programs/fasta/fasta.python3-3.python3", line 127, in main
    repeat_fasta(alu, n * 2)
  File "/home/dundee/work/pybenchmarks/bencher/programs/fasta/fasta.python3-3.python3", line 52, in repeat_fasta
    s = bytearray(ss, encoding='utf8')
TypeError: __new__() got an unexpected keyword argument 'encoding'
