
Mon, 18 Jun 2018 12:07:06 GMT

COMMAND LINE:
/usr/bin/graalpython knucleotide.graal-3.graal 0 < knucleotide-input10000.txt

PROGRAM FAILED 


PROGRAM OUTPUT:

Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Error in sys.excepthook:

Traceback (most recent call last):
  File "sys", line 135, in __print_traceback__
  File "/usr/lib/jvm/java-8-graal/jre/languages/python/lib-python/3/traceback.py", line 99, in print_exception
  File "/usr/lib/jvm/java-8-graal/jre/languages/python/lib-python/3/traceback.py", line 495, in TracebackException.__init__
  File "/usr/lib/jvm/java-8-graal/jre/languages/python/lib-python/3/traceback.py", line 358, in StackSummary.extract
  File "property", line 79, in property.__get__
  File "/usr/lib/jvm/java-8-graal/jre/languages/python/lib-python/3/traceback.py", line 282, in FrameSummary.line
  File "/usr/lib/jvm/java-8-graal/jre/languages/python/lib-python/3/linecache.py", line 16, in getline
  File "/usr/lib/jvm/java-8-graal/jre/languages/python/lib-python/3/linecache.py", line 47, in getlines
  File "/usr/lib/jvm/java-8-graal/jre/languages/python/lib-python/3/linecache.py", line 141, in updatecache
TypeError: can't concat bytes to str

Original exception was:

Traceback (most recent call last):
  File "knucleotide.graal-3.graal", line 6, in <module>
ImportError: cannot import name 'cpu_count'
