
 Fri, 30 Oct 2020 20:17:11 GMT

MAKE:
make[1]: Vstupuje se do adresáře „/home/dundee/work/pybenchmarks/bencher/tmp/pidigits/tmp“
nuitka3 --remove-output pidigits.nuitka-3.nuitka
cp pidigits.nuitka-3.nuitka.bin pidigits.nuitka-3.nuitka_run
make[1]: Opouští se adresář „/home/dundee/work/pybenchmarks/bencher/tmp/pidigits/tmp“
6.34s to complete and log all make actions

COMMAND LINE:
 ./pidigits.nuitka-3.nuitka_run 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "/home/dundee/work/pybenchmarks/bencher/tmp/pidigits/tmp/pidigits.nuitka-3.nuitka", line 11, in <module>
    from gmpy2 import mpz
ModuleNotFoundError: No module named 'gmpy2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dundee/work/pybenchmarks/bencher/tmp/pidigits/tmp/pidigits.nuitka-3.nuitka", line 13, in <module>
    from gmpy_cffi import mpz
ModuleNotFoundError: No module named 'gmpy_cffi'
