
 Fri, 30 Oct 2020 21:36:42 GMT

COMMAND LINE:
 /usr/lib/jvm/java-8-graalvm/bin/graalpython pidigits.graal-3.graal 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "/home/dundee/work/pybenchmarks/bencher/programs/pidigits/pidigits.python3-3.python3", line 11, in <module 'pidigits.python3-3.python3'>
    from gmpy2 import mpz
  File "/importlib/_bootstrap.py", line 991, in _find_and_load
ModuleNotFoundError: No module named 'gmpy2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dundee/work/pybenchmarks/bencher/programs/pidigits/pidigits.python3-3.python3", line 13, in <module 'pidigits.python3-3.python3'>
    from gmpy_cffi import mpz
  File "/importlib/_bootstrap.py", line 991, in _find_and_load
ModuleNotFoundError: No module named 'gmpy_cffi'
