
 Thu, 18 Jun 2020 09:34:37 GMT

COMMAND LINE:
 /usr/bin/python3.10 threadring.python-dev 5000000

PROGRAM FAILED 


PROGRAM OUTPUT:
181

Traceback (most recent call last):
  File "/home/dundee/workspace/benchmarksgame/bencher/tmp/threadring/tmp/threadring.python-dev", line 22, in worker
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dundee/workspace/benchmarksgame/bencher/tmp/threadring/tmp/threadring.python-dev", line 34, in <module>
    main()
  File "/home/dundee/workspace/benchmarksgame/bencher/tmp/threadring/tmp/threadring.python-dev", line 30, in main
    n = send(n)
RuntimeError: generator raised StopIteration
